/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.config.year_x=4;a.config.year_y=3;a.xy.year_top=0;a.templates.year_date=function(q){return a.date.date_to_str(a.locale.labels.year_tab+" %Y")(q)};a.templates.year_month=a.date.date_to_str("%F");a.templates.year_scale_date=a.date.date_to_str("%D");a.templates.year_tooltip=function(a,v,w){return w.text};(function(){function q(a){return n(a,function(a){return a.nodeName.toLowerCase()=="td"})}function v(a){return n(a,function(a){return a.nodeName.toLowerCase()=="table"})}
function w(a){a=v(a);return n(a,function(a){return a.hasAttribute&&a.hasAttribute("date")})}function n(a,b){for(;a&&!b(a);)a=a.parentNode;return a}var l=function(){return a._mode=="year"};a.dblclick_dhx_month_head=function(a){if(l()){var b=a.target||a.srcElement;if(b.parentNode.className.indexOf("dhx_before")!=-1||b.parentNode.className.indexOf("dhx_after")!=-1)return!1;var e=this.templates.xml_date(b.parentNode.parentNode.parentNode.parentNode.parentNode.parentNode.getAttribute("date"));e.setDate(parseInt(b.innerHTML,
10));var f=this.date.add(e,1,"day");!this.config.readonly&&this.config.dblclick_create&&this.addEventNow(e.valueOf(),f.valueOf(),a)}};var x=a.changeEventId;a.changeEventId=function(){x.apply(this,arguments);l()&&this.year_view(!0)};var y=a.render_data,z=a.date.date_to_str("%Y/%m/%d"),A=a.date.str_to_date("%Y/%m/%d");a.render_data=function(a){if(!l())return y.apply(this,arguments);for(var b=0;b<a.length;b++)this._year_render_event(a[b])};var B=a.clear_view;a.clear_view=function(){if(!l())return B.apply(this,
arguments);for(var a in o)if(o.hasOwnProperty(a)){var b=o[a];b.className="dhx_month_head";b.setAttribute("date","")}o={}};a._hideToolTip=function(){if(this._tooltip)this._tooltip.style.display="none",this._tooltip.date=new Date(9999,1,1)};a._showToolTip=function(c,b,e,f){if(this._tooltip){if(this._tooltip.date.valueOf()==c.valueOf())return;this._tooltip.innerHTML=""}else{var d=this._tooltip=document.createElement("DIV");d.className="dhx_year_tooltip";document.body.appendChild(d);d.onclick=a._click.dhx_cal_data}for(var i=
this.getEvents(c,this.date.add(c,1,"day")),m="",j=0;j<i.length;j++){var p=i[j],g=p.color?"background:"+p.color+";":"",k=p.textColor?"color:"+p.textColor+";":"";m+="<div class='dhx_tooltip_line' style='"+g+""+k+"' event_id='"+i[j].id+"'>";m+="<div class='dhx_tooltip_date' style='"+g+""+k+"'>"+(i[j]._timed?this.templates.event_date(i[j].start_date):"")+"</div>";m+="<div class='dhx_event_icon icon_details'>&nbsp;</div>";m+=this.templates.year_tooltip(i[j].start_date,i[j].end_date,i[j])+"</div>"}this._tooltip.style.display=
"";this._tooltip.style.top="0px";this._tooltip.style.left=document.body.offsetWidth-b.left-this._tooltip.offsetWidth<0?b.left-this._tooltip.offsetWidth+"px":b.left+f.offsetWidth+"px";this._tooltip.date=c;this._tooltip.innerHTML=m;this._tooltip.style.top=document.body.offsetHeight-b.top-this._tooltip.offsetHeight<0?b.top-this._tooltip.offsetHeight+f.offsetHeight+"px":b.top+"px"};a._init_year_tooltip=function(){dhtmlxEvent(a._els.dhx_cal_data[0],"mouseover",function(c){if(l()){var c=c||event,b=c.target||
c.srcElement;if(b.tagName.toLowerCase()=="a")b=b.parentNode;(b.className||"").indexOf("dhx_year_event")!=-1?a._showToolTip(A(b.getAttribute("date")),getOffset(b),c,b):a._hideToolTip()}});this._init_year_tooltip=function(){}};a.attachEvent("onSchedulerResize",function(){return l()?(this.year_view(!0),!1):!0});a._get_year_cell=function(a){var b=a.getMonth()+12*(a.getFullYear()-this._min_date.getFullYear())-this.week_starts._month,e=this._els.dhx_cal_data[0].childNodes[b],a=this.week_starts[b]+a.getDate()-
1;return e.childNodes[2].firstChild.rows[Math.floor(a/7)].cells[a%7].firstChild};var o={};a._mark_year_date=function(a,b){var e=z(a),f=this._get_year_cell(a),d=this.templates.event_class(b.start_date,b.end_date,b);if(!o[e])f.className="dhx_month_head dhx_year_event",f.setAttribute("date",e),o[e]=f;f.className+=d?" "+d:""};a._unmark_year_date=function(a){this._get_year_cell(a).className="dhx_month_head"};a._year_render_event=function(a){for(var b=a.start_date,b=b.valueOf()<this._min_date.valueOf()?
this._min_date:this.date.date_part(new Date(b));b<a.end_date;)if(this._mark_year_date(b,a),b=this.date.add(b,1,"day"),b.valueOf()>=this._max_date.valueOf())break};a.year_view=function(c){if(c){var b=a.xy.scale_height;a.xy.scale_height=-1}a._els.dhx_cal_header[0].style.display=c?"none":"";a.set_sizes();if(c)a.xy.scale_height=b;a._table_view=c;if(!this._load_mode||!this._load())if(c){a._init_year_tooltip();a._reset_year_scale();if(a._load_mode&&a._load())return a._render_wait=!0;a.render_view_data()}else a._hideToolTip()};
a._reset_year_scale=function(){this._cols=[];this._colsS={};var c=[],b=this._els.dhx_cal_data[0],e=this.config;b.scrollTop=0;b.innerHTML="";var f=Math.floor(parseInt(b.style.width)/e.year_x),d=Math.floor((parseInt(b.style.height)-a.xy.year_top)/e.year_y);d<190&&(d=190,f=Math.floor((parseInt(b.style.width)-a.xy.scroll_width)/e.year_x));for(var i=f-11,m=0,j=document.createElement("div"),p=this.date.week_start(a._currentDate()),g=0;g<7;g++)this._cols[g]=Math.floor(i/(7-g)),this._render_x_header(g,m,
p,j),p=this.date.add(p,1,"day"),i-=this._cols[g],m+=this._cols[g];j.lastChild.className+=" dhx_scale_bar_last";for(var k=this.date[this._mode+"_start"](this.date.copy(this._date)),l=k,g=0;g<e.year_y;g++)for(var t=0;t<e.year_x;t++){var h=document.createElement("DIV");h.style.cssText="position:absolute;";h.setAttribute("date",this.templates.xml_format(k));h.innerHTML="<div class='dhx_year_month'></div><div class='dhx_year_week'>"+j.innerHTML+"</div><div class='dhx_year_body'></div>";h.childNodes[0].innerHTML=
this.templates.year_month(k);for(var o=this.date.week_start(k),n=this._reset_month_scale(h.childNodes[2],k,o),r=h.childNodes[2].firstChild.rows,s=r.length;s<6;s++){r[0].parentNode.appendChild(r[0].cloneNode(!0));for(var u=0;u<r[s].childNodes.length;u++)r[s].childNodes[u].className="dhx_after",r[s].childNodes[u].firstChild.innerHTML=a.templates.month_day(n),n=a.date.add(n,1,"day")}b.appendChild(h);h.childNodes[1].style.height=h.childNodes[1].childNodes[0].offsetHeight+"px";var q=Math.round((d-190)/
2);h.style.marginTop=q+"px";this.set_xy(h,f-10,d-q-10,f*t+5,d*g+5+a.xy.year_top);c[g*e.year_x+t]=(k.getDay()-(this.config.start_on_monday?1:0)+7)%7;k=this.date.add(k,1,"month")}this._els.dhx_cal_date[0].innerHTML=this.templates[this._mode+"_date"](l,k,this._mode);this.week_starts=c;c._month=l.getMonth();this._min_date=l;this._max_date=k};var C=a.getActionData;a.getActionData=function(c){function b(b){b=w(b);if(!b)return null;var c=b.getAttribute("date");return!c?null:a.date.week_start(a.templates.xml_date(c))}
function e(a){var b=v(a);if(!b)return null;for(var c=0,d=0,c=0,e=b.rows.length;c<e;c++){for(var f=b.rows[c].getElementsByTagName("td"),d=0,h=f.length;d<h;d++)if(f[d]==a)break;if(d<h)break}return c<e?{day:d,week:c}:null}if(!l())return C.apply(a,arguments);var f=c?c.target:event.srcElement,d=b(f),i=q(f),m=e(i);m&&d?(d=a.date.add(d,m.week,"week"),d=a.date.add(d,m.day,"day")):d=null;return{date:d,section:null}};var D=a._locate_event;a._locate_event=function(c){if(!l())return D.apply(a,arguments);var b=
n(c,function(a){return a.className&&a.className.indexOf("dhx_year_event")!=-1&&a.hasAttribute&&a.hasAttribute("date")});if(!b||!b.hasAttribute("date"))return null;var e=a.templates.xml_date(b.getAttribute("date")),f=a.getEvents(e,a.date.add(e,1,"day"));return!f.length?null:f[0].id}})()});
