/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(a._temp_matrix_scope=function(){function I(){for(var b=a.get_visible_events(),d=[],c=0;c<this.y_unit.length;c++)d[c]=[];d[e]||(d[e]=[]);for(c=0;c<b.length;c++){for(var e=this.order[b[c][this.y_property]],i=0;this._trace_x[i+1]&&b[c].start_date>=this._trace_x[i+1];)i++;for(;this._trace_x[i]&&b[c].end_date>this._trace_x[i];)d[e][i]||(d[e][i]=[]),d[e][i].push(b[c]),i++}return d}function y(b,d,c){var e=0,i=c._step,f=c.round_position,m=0,g=d?b.end_date:b.start_date;if(g.valueOf()>
a._max_date.valueOf())g=a._max_date;var j=g-a._min_date_timeline;if(j>0){var n=a._get_date_index(c,g);a._ignores[n]&&(f=!0);for(var k=0;k<n;k++)e+=a._cols[k];var r=a.date.add(a._min_date_timeline,a.matrix[a._mode].x_step*n,a.matrix[a._mode].x_unit);f?+g>+r&&d&&(m=a._cols[n]):(j=g-r,c.first_hour||c.last_hour?(j-=c._start_correction,j<0&&(j=0),m=Math.round(j/i),m>a._cols[n]&&(m=a._cols[n])):m=Math.round(j/i))}e+=d?j!=0&&!f?m-12:m-14:m+1;return e}function v(b,d){var c=a._get_date_index(this,b),e=this._trace_x[c];
d&&+b!=+this._trace_x[c]&&(e=this._trace_x[c+1]?this._trace_x[c+1]:a.date.add(this._trace_x[c],this.x_step,this.x_unit));return new Date(e)}function J(b){var d="";if(b&&this.render!="cell"){b.sort(this.sort||function(a,b){return a.start_date.valueOf()==b.start_date.valueOf()?a.id>b.id?1:-1:a.start_date>b.start_date?1:-1});for(var c=[],e=b.length,i=0;i<e;i++){var f=b[i];f._inner=!1;for(var m=this.round_position?v.apply(this,[f.start_date,!1]):f.start_date,g=this.round_position?v.apply(this,[f.end_date,
!0]):f.end_date;c.length;){var j=c[c.length-1];if(j.end_date.valueOf()<=m.valueOf())c.splice(c.length-1,1);else break}for(var n=!1,k=0;k<c.length;k++){var r=c[k];if(r.end_date.valueOf()<=m.valueOf()){n=!0;f._sorder=r._sorder;c.splice(k,1);f._inner=!0;break}}if(c.length)c[c.length-1]._inner=!0;if(!n)if(c.length)if(c.length<=c[c.length-1]._sorder){if(c[c.length-1]._sorder)for(var h=0;h<c.length;h++){for(var q=!1,o=0;o<c.length;o++)if(c[o]._sorder==h){q=!0;break}if(!q){f._sorder=h;break}}else f._sorder=
0;f._inner=!0}else{for(var q=c[0]._sorder,p=1;p<c.length;p++)if(c[p]._sorder>q)q=c[p]._sorder;f._sorder=q+1;f._inner=!1}else f._sorder=0;c.push(f);c.length>(c.max_count||0)?(c.max_count=c.length,f._count=c.length):f._count=f._count?f._count:1}for(var l=0;l<b.length;l++)b[l]._count=c.max_count;for(var s=0;s<e;s++)d+=a.render_timeline_event.call(this,b[s],!1)}return d}function K(b){var d="<table style='table-layout:fixed;' cellspacing='0' cellpadding='0'>",c=[];a._load_mode&&a._load();if(this.render==
"cell")c=I.call(this);else for(var e=a.get_visible_events(),i=this.order,f=0;f<e.length;f++){var m=e[f],g=m[this.y_property],j=this.order[g];if(this.show_unassigned&&!g)for(var n in i){if(i.hasOwnProperty(n)){j=i[n];c[j]||(c[j]=[]);var k=a._lame_copy({},m);k[this.y_property]=n;c[j].push(k)}}else c[j]||(c[j]=[]),c[j].push(m)}for(var r=0,h=0;h<a._cols.length;h++)r+=a._cols[h];var q=new Date,o=a._cols.length-a._ignores_detected;this._step=q=(a.date.add(q,this.x_step*o,this.x_unit)-q-(this._start_correction+
this._end_correction)*o)/r;this._summ=r;var p=a._colsS.heights=[];this._events_height={};this._section_height={};for(h=0;h<this.y_unit.length;h++){var l=this._logic(this.render,this.y_unit[h],this);a._merge(l,{height:this.dy});if(this.section_autoheight){if(this.y_unit.length*l.height<b.offsetHeight)l.height=Math.max(l.height,Math.floor((b.offsetHeight-1)/this.y_unit.length));this._section_height[this.y_unit[h].key]=l.height}a._merge(l,{tr_className:"",style_height:"height:"+l.height+"px;",style_width:"width:"+
(this.dx-1)+"px;",td_className:"dhx_matrix_scell"+(a.templates[this.name+"_scaley_class"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h])?" "+a.templates[this.name+"_scaley_class"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h]):""),td_content:a.templates[this.name+"_scale_label"](this.y_unit[h].key,this.y_unit[h].label,this.y_unit[h]),summ_width:"width:"+r+"px;",table_className:""});var s=J.call(this,c[h]);if(this.fit_events){var t=this._events_height[this.y_unit[h].key]||0;l.height=
t>l.height?t:l.height;l.style_height="height:"+l.height+"px;";this._section_height[this.y_unit[h].key]=l.height}d+="<tr class='"+l.tr_className+"' style='"+l.style_height+"'><td class='"+l.td_className+"' style='"+l.style_width+" height:"+(l.height-1)+"px;'>"+l.td_content+"</td>";if(this.render=="cell")for(f=0;f<a._cols.length;f++)d+=a._ignores[f]?"<td></td>":"<td class='dhx_matrix_cell "+a.templates[this.name+"_cell_class"](c[h][f],this._trace_x[f],this.y_unit[h])+"' style='width:"+(a._cols[f]-1)+
"px'><div style='width:"+(a._cols[f]-1)+"px'>"+a.templates[this.name+"_cell_value"](c[h][f])+"</div></td>";else{d+="<td><div style='"+l.summ_width+" "+l.style_height+" position:relative;' class='dhx_matrix_line'>";d+=s;d+="<table class='"+l.table_className+"' cellpadding='0' cellspacing='0' style='"+l.summ_width+" "+l.style_height+"' >";for(f=0;f<a._cols.length;f++)d+=a._ignores[f]?"<td></td>":"<td class='dhx_matrix_cell "+a.templates[this.name+"_cell_class"](c[h],this._trace_x[f],this.y_unit[h])+
"' style='width:"+(a._cols[f]-1)+"px'><div style='width:"+(a._cols[f]-1)+"px'></div></td>";d+="</table>";d+="</div></td>"}d+="</tr>"}d+="</table>";this._matrix=c;b.innerHTML=d;a._rendered=[];for(var u=a._obj.getElementsByTagName("DIV"),h=0;h<u.length;h++)u[h].getAttribute("event_id")&&a._rendered.push(u[h]);this._scales={};for(h=0;h<b.firstChild.rows.length;h++){p.push(b.firstChild.rows[h].offsetHeight);var B=this.y_unit[h].key,C=this._scales[B]=a._isRender("cell")?b.firstChild.rows[h]:b.firstChild.rows[h].childNodes[1].getElementsByTagName("div")[0];
a.callEvent("onScaleAdd",[C,B])}}function L(b){var d=a.xy.scale_height,c=this._header_resized||a.xy.scale_height;a._cols=[];a._colsS={height:0};this._trace_x=[];var e=a._x-this.dx-a.xy.scroll_width,i=[this.dx],f=a._els.dhx_cal_header[0];f.style.width=i[0]+e+"px";a._min_date_timeline=a._min_date;var m=a.config.preserve_scale_length,g=a._min_date;a._process_ignores(g,this.x_size,this.x_unit,this.x_step,m);var j=this.x_size+(m?a._ignores_detected:0);if(j!=this.x_size)a._max_date=a.date.add(a._min_date,
j*this.x_step,this.x_unit);for(var n=j-a._ignores_detected,k=0;k<j;k++)this._trace_x[k]=new Date(g),g=a.date.add(g,this.x_step,this.x_unit),a._ignores[k]?(a._cols[k]=0,n++):a._cols[k]=Math.floor(e/(n-k)),e-=a._cols[k],i[k+1]=i[k]+a._cols[k];b.innerHTML="<div></div>";if(this.second_scale){for(var r=this.second_scale.x_unit,h=[this._trace_x[0]],q=[],o=[this.dx,this.dx],p=0,l=0;l<this._trace_x.length;l++){var s=this._trace_x[l],t=F(r,s,h[p]);t&&(++p,h[p]=s,o[p+1]=o[p]);var u=p+1;q[p]=a._cols[l]+(q[p]||
0);o[u]+=a._cols[l]}b.innerHTML="<div></div><div></div>";var B=b.firstChild;B.style.height=c+"px";var C=b.lastChild;C.style.position="relative";for(var w=0;w<h.length;w++){var D=h[w],z=a.templates[this.name+"_second_scalex_class"](D),A=document.createElement("DIV");A.className="dhx_scale_bar dhx_second_scale_bar"+(z?" "+z:"");a.set_xy(A,q[w]-1,c-3,o[w],0);A.innerHTML=a.templates[this.name+"_second_scale_date"](D);B.appendChild(A)}}a.xy.scale_height=c;for(var b=b.lastChild,x=0;x<this._trace_x.length;x++)if(!a._ignores[x]){g=
this._trace_x[x];a._render_x_header(x,i[x],g,b);var y=a.templates[this.name+"_scalex_class"](g);y&&(b.lastChild.className+=" "+y)}a.xy.scale_height=d;var v=this._trace_x;b.onclick=function(b){var c=G(b);c&&a.callEvent("onXScaleClick",[c.x,v[c.x],b||event])};b.ondblclick=function(b){var c=G(b);c&&a.callEvent("onXScaleDblClick",[c.x,v[c.x],b||event])}}function F(b,d,c){switch(b){case "hour":return d.getHours()!=c.getHours()||F("day",d,c);case "day":return!(d.getDate()==c.getDate()&&d.getMonth()==c.getMonth()&&
d.getFullYear()==c.getFullYear());case "week":return!(a.date.getISOWeek(d)==a.date.getISOWeek(c)&&d.getFullYear()==c.getFullYear());case "month":return!(d.getMonth()==c.getMonth()&&d.getFullYear()==c.getFullYear());case "year":return d.getFullYear()!=c.getFullYear();default:return!1}}function M(b){if(b){a.set_sizes();H();var d=a._min_date;L.call(this,a._els.dhx_cal_header[0]);K.call(this,a._els.dhx_cal_data[0]);a._min_date=d;a._els.dhx_cal_date[0].innerHTML=a.templates[this.name+"_date"](a._min_date,
a._max_date);a._mark_now&&a._mark_now()}E()}function E(){if(a._tooltip)a._tooltip.style.display="none",a._tooltip.date=""}function N(b,d,c){if(b.render=="cell"){var e=d.x+"_"+d.y,i=b._matrix[d.y][d.x];if(!i)return E();i.sort(function(a,b){return a.start_date>b.start_date?1:-1});if(a._tooltip){if(a._tooltip.date==e)return;a._tooltip.innerHTML=""}else{var f=a._tooltip=document.createElement("DIV");f.className="dhx_year_tooltip";document.body.appendChild(f);f.onclick=a._click.dhx_cal_data}for(var m=
"",g=0;g<i.length;g++){var j=i[g].color?"background-color:"+i[g].color+";":"",n=i[g].textColor?"color:"+i[g].textColor+";":"";m+="<div class='dhx_tooltip_line' event_id='"+i[g].id+"' style='"+j+""+n+"'>";m+="<div class='dhx_tooltip_date'>"+(i[g]._timed?a.templates.event_date(i[g].start_date):"")+"</div>";m+="<div class='dhx_event_icon icon_details'>&nbsp;</div>";m+=a.templates[b.name+"_tooltip"](i[g].start_date,i[g].end_date,i[g])+"</div>"}a._tooltip.style.display="";a._tooltip.style.top="0px";a._tooltip.style.left=
document.body.offsetWidth-c.left-a._tooltip.offsetWidth<0?c.left-a._tooltip.offsetWidth+"px":c.left+d.src.offsetWidth+"px";a._tooltip.date=e;a._tooltip.innerHTML=m;a._tooltip.style.top=document.body.offsetHeight-c.top-a._tooltip.offsetHeight<0?c.top-a._tooltip.offsetHeight+d.src.offsetHeight+"px":c.top+"px"}}function H(){dhtmlxEvent(a._els.dhx_cal_data[0],"mouseover",function(b){var d=a.matrix[a._mode];if(d&&d.render=="cell"){if(d){var c=a._locate_cell_timeline(b),b=b||event,e=b.target||b.srcElement;
if(c)return N(d,c,getOffset(c.src))}E()}});H=function(){}}function O(a){for(var d=a.parentNode.childNodes,c=0;c<d.length;c++)if(d[c]==a)return c;return-1}function G(a){for(var a=a||event,d=a.target?a.target:a.srcElement;d&&d.tagName!="DIV";)d=d.parentNode;if(d&&d.tagName=="DIV"){var c=d.className.split(" ")[0];if(c=="dhx_scale_bar")return{x:O(d),y:-1,src:d,scale:!0}}}a.matrix={};a._merge=function(a,d){for(var c in d)typeof a[c]=="undefined"&&(a[c]=d[c])};a.createTimelineView=function(b){a._skin_init();
a._merge(b,{section_autoheight:!0,name:"matrix",x:"time",y:"time",x_step:1,x_unit:"hour",y_unit:"day",y_step:1,x_start:0,x_size:24,y_start:0,y_size:7,render:"cell",dx:200,dy:50,event_dy:a.xy.bar_height-5,event_min_dy:a.xy.bar_height-5,resize_events:!0,fit_events:!0,show_unassigned:!1,second_scale:!1,round_position:!1,_logic:function(b,c,d){var g={};a.checkEvent("onBeforeSectionRender")&&(g=a.callEvent("onBeforeSectionRender",[b,c,d]));return g}});b._original_x_start=b.x_start;if(b.x_unit!="day")b.first_hour=
b.last_hour=0;b._start_correction=b.first_hour?b.first_hour*36E5:0;b._end_correction=b.last_hour?(24-b.last_hour)*36E5:0;a.checkEvent("onTimelineCreated")&&a.callEvent("onTimelineCreated",[b]);var d=a.render_data;a.render_data=function(c,f){if(this._mode==b.name)if(f&&!b.show_unassigned&&b.render!="cell")for(var e=0;e<c.length;e++)this.clear_event(c[e]),this.render_timeline_event.call(this.matrix[this._mode],c[e],!0);else a._renderMatrix.call(b,!0,!0);else return d.apply(this,arguments)};a.matrix[b.name]=
b;a.templates[b.name+"_cell_value"]=function(a){return a?a.length:""};a.templates[b.name+"_cell_class"]=function(){return""};a.templates[b.name+"_scalex_class"]=function(){return""};a.templates[b.name+"_second_scalex_class"]=function(){return""};a.templates[b.name+"_scaley_class"]=function(){return""};a.templates[b.name+"_scale_label"]=function(a,b){return b};a.templates[b.name+"_tooltip"]=function(a,b,c){return c.text};a.templates[b.name+"_date"]=function(b,c){return b.getDay()==c.getDay()&&c-b<
864E5||+b==+a.date.date_part(new Date(c))||+a.date.add(b,1,"day")==+c&&c.getHours()==0&&c.getMinutes()==0?a.templates.day_date(b):b.getDay()!=c.getDay()&&c-b<864E5?a.templates.day_date(b)+" &ndash; "+a.templates.day_date(c):a.templates.week_date(b,c)};a.templates[b.name+"_scale_date"]=a.date.date_to_str(b.x_date||a.config.hour_date);a.templates[b.name+"_second_scale_date"]=a.date.date_to_str(b.second_scale&&b.second_scale.x_date?b.second_scale.x_date:a.config.hour_date);a.date["add_"+b.name]=function(c,
d){var e=a.date.add(c,(b.x_length||b.x_size)*d*b.x_step,b.x_unit);if(b.x_unit=="minute"||b.x_unit=="hour"){var g=b.x_length||b.x_size,j=b.x_unit=="hour"?b.x_step*60:b.x_step;if(j*g%1440)if(+a.date.date_part(new Date(c))==+a.date.date_part(new Date(e)))b.x_start+=d*g;else{var n=1440/(g*j)-1,k=Math.round(n*g);d>0?b.x_start-=k:b.x_start=k+b.x_start}}return e};a.attachEvent("onBeforeTodayDisplayed",function(){b.x_start=b._original_x_start;return!0});a.date[b.name+"_start"]=function(c){var d=a.date[b.x_unit+
"_start"]||a.date.day_start,e=d.call(a.date,c);return e=a.date.add(e,b.x_step*b.x_start,b.x_unit)};a.attachEvent("onSchedulerResize",function(){return this._mode==b.name?(a._renderMatrix.call(b,!0,!0),!1):!0});a.attachEvent("onOptionsLoad",function(){b.order={};a.callEvent("onOptionsLoadStart",[]);for(var c=0;c<b.y_unit.length;c++)b.order[b.y_unit[c].key]=c;a.callEvent("onOptionsLoadFinal",[]);a._date&&b.name==a._mode&&a.setCurrentView(a._date,a._mode)});a.callEvent("onOptionsLoad",[b]);a[b.name+
"_view"]=function(){a._renderMatrix.apply(b,arguments)};var c=new Date,e=a.date.add(c,b.x_step,b.x_unit).valueOf()-c.valueOf();a["mouse_"+b.name]=function(c){var d=this._drag_event;if(this._drag_id)d=this.getEvent(this._drag_id),this._drag_event._dhx_changed=!0;c.x-=b.dx;for(var e=0,g=0,j=0;g<=this._cols.length-1;g++){var n=this._cols[g];e+=n;if(e>c.x){var k=(c.x-(e-n))/n,k=k<0?0:k;break}}b.round_position&&(k>=0.9&&g++,k=0);if(g==0&&this._ignores[0]){g=1;for(k=0;this._ignores[g];)g++}else if(g==this._cols.length&&
this._ignores[g-1]){g=this._cols.length-1;for(k=0;this._ignores[g];)g--;g++}for(e=0;j<this._colsS.heights.length;j++)if(e+=this._colsS.heights[j],e>c.y)break;c.fields={};b.y_unit[j]||(j=b.y_unit.length-1);if(j>=0&&b.y_unit[j]&&(c.section=c.fields[b.y_property]=b.y_unit[j].key,d)){if(d[b.y_property]!=c.section){var r=a._get_timeline_event_height(d,b);d._sorder=a._get_dnd_order(d._sorder,r,b._section_height[c.section])}d[b.y_property]=c.section}c.x=0;c.force_redraw=!0;c.custom=!0;var h;if(g>=b._trace_x.length)h=
a.date.add(b._trace_x[b._trace_x.length-1],b.x_step,b.x_unit),b._end_correction&&(h=new Date(h-b._end_correction));else{var q=k*n*b._step+b._start_correction;h=new Date(+b._trace_x[g]+q)}if(this._drag_mode=="move"&&this._drag_id&&this._drag_event){var d=this.getEvent(this._drag_id),o=this._drag_event;c._ignores=this._ignores_detected||b._start_correction||b._end_correction;if(!o._move_delta&&(o._move_delta=(d.start_date-h)/6E4,this.config.preserve_length&&c._ignores))o._move_delta=this._get_real_event_length(d.start_date,
h,b),o._event_length=this._get_real_event_length(d.start_date,d.end_date,b);if(this.config.preserve_length&&c._ignores){var p=o._event_length,l=this._get_fictional_event_length(h,o._move_delta,b,!0);h=new Date(h-l)}else h=a.date.add(h,o._move_delta,"minute")}if(this._drag_mode=="resize"&&d){var s=!!(Math.abs(d.start_date-h)<Math.abs(d.end_date-h));if(b._start_correction||b._end_correction){var t=!this._drag_event||this._drag_event._resize_from_start==void 0;t||Math.abs(d.end_date-d.start_date)<=6E4*
this.config.time_step?this._drag_event._resize_from_start=c.resize_from_start=s:c.resize_from_start=this._drag_event._resize_from_start}else c.resize_from_start=s}if(b.round_position)switch(this._drag_mode){case "move":if(!this.config.preserve_length&&(h=v.call(b,h,!1),b.x_unit=="day"))c.custom=!1;break;case "resize":if(this._drag_event){if(this._drag_event._resize_from_start==null)this._drag_event._resize_from_start=c.resize_from_start;c.resize_from_start=this._drag_event._resize_from_start;h=v.call(b,
h,!this._drag_event._resize_from_start)}}c.y=Math.round((h-this._min_date)/(6E4*this.config.time_step));c.shift=this.config.time_step;return c}};a._get_timeline_event_height=function(a,d){var c=a[d.y_property],e=d.event_dy;d.event_dy=="full"&&(e=d.section_autoheight?d._section_height[c]-6:d.dy-3);d.resize_events&&(e=Math.max(Math.floor(e/a._count),d.event_min_dy));return e};a._get_timeline_event_y=function(b,d){var c=b,e=2+c*d+(c?c*2:0);a.config.cascade_event_display&&(e=2+c*a.config.cascade_event_margin+
(c?c*2:0));return e};a.render_timeline_event=function(b,d){var c=b[this.y_property];if(!c)return"";var e=b._sorder,i=y(b,!1,this),f=y(b,!0,this),m=a._get_timeline_event_height(b,this),g=m-2;!b._inner&&this.event_dy=="full"&&(g=(g+2)*(b._count-e)-2);var j=a._get_timeline_event_y(b._sorder,m),n=m+j+2;if(!this._events_height[c]||this._events_height[c]<n)this._events_height[c]=n;var k=a.templates.event_class(b.start_date,b.end_date,b),k="dhx_cal_event_line "+(k||""),r=b.color?"background:"+b.color+";":
"",h=b.textColor?"color:"+b.textColor+";":"",q=a.templates.event_bar_text(b.start_date,b.end_date,b),o='<div event_id="'+b.id+'" class="'+k+'" style="'+r+""+h+"position:absolute; top:"+j+"px; height: "+g+"px; left:"+i+"px; width:"+Math.max(0,f-i)+"px;"+(b._text_style||"")+'">';if(a.config.drag_resize&&!a.config.readonly){var p="dhx_event_resize";o+="<div class='"+p+" "+p+"_start' style='height: "+g+"px;'></div><div class='"+p+" "+p+"_end' style='height: "+g+"px;'></div>"}o+=q+"</div>";if(d){var l=
document.createElement("DIV");l.innerHTML=o;var s=this.order[c],t=a._els.dhx_cal_data[0].firstChild.rows[s].cells[1].firstChild;a._rendered.push(l.firstChild);t.appendChild(l.firstChild)}else return o};a._renderMatrix=function(b,d){if(!d)a._els.dhx_cal_data[0].scrollTop=0;a._min_date=a.date[this.name+"_start"](a._date);a._max_date=a.date.add(a._min_date,this.x_size*this.x_step,this.x_unit);a._table_view=!0;if(this.second_scale){if(b&&!this._header_resized)this._header_resized=a.xy.scale_height,a.xy.scale_height*=
2,a._els.dhx_cal_header[0].className+=" dhx_second_cal_header";if(!b&&this._header_resized){a.xy.scale_height/=2;this._header_resized=!1;var c=a._els.dhx_cal_header[0];c.className=c.className.replace(/ dhx_second_cal_header/gi,"")}}M.call(this,b)};a._locate_cell_timeline=function(b){for(var b=b||event,d=b.target?b.target:b.srcElement,c={},e=a.matrix[a._mode],i=a.getActionData(b),f=0;f<e._trace_x.length-1;f++)if(+i.date<e._trace_x[f+1])break;c.x=f;c.y=e.order[i.section];var m=a._isRender("cell")?1:
0;c.src=e._scales[i.section]?e._scales[i.section].getElementsByTagName("td")[f+m]:null;for(var g=!1;c.x==0&&d.className!="dhx_cal_data"&&d.parentNode;)if(d.className.split(" ")[0]=="dhx_matrix_scell"){g=!0;break}else d=d.parentNode;if(g)c.x=-1,c.src=d,c.scale=!0;return c};var P=a._click.dhx_cal_data;a._click.dhx_marked_timespan=a._click.dhx_cal_data=function(b){var d=P.apply(this,arguments),c=a.matrix[a._mode];if(c){var e=a._locate_cell_timeline(b);e&&(e.scale?a.callEvent("onYScaleClick",[e.y,c.y_unit[e.y],
b||event]):a.callEvent("onCellClick",[e.x,e.y,c._trace_x[e.x],(c._matrix[e.y]||{})[e.x]||[],b||event]))}return d};a.dblclick_dhx_marked_timespan=a.dblclick_dhx_matrix_cell=function(b){var d=a.matrix[a._mode];if(d){var c=a._locate_cell_timeline(b);c&&(c.scale?a.callEvent("onYScaleDblClick",[c.y,d.y_unit[c.y],b||event]):a.callEvent("onCellDblClick",[c.x,c.y,d._trace_x[c.x],(d._matrix[c.y]||{})[c.x]||[],b||event]))}};a.dblclick_dhx_matrix_scell=function(b){return a.dblclick_dhx_matrix_cell(b)};a._isRender=
function(b){return a.matrix[a._mode]&&a.matrix[a._mode].render==b};a.attachEvent("onCellDblClick",function(b,d,c,e,i){if(!(this.config.readonly||i.type=="dblclick"&&!this.config.dblclick_create)){var f=a.matrix[a._mode],m={};m.start_date=f._trace_x[b];m.end_date=f._trace_x[b+1]?f._trace_x[b+1]:a.date.add(f._trace_x[b],f.x_step,f.x_unit);if(f._start_correction)m.start_date=new Date(m.start_date*1+f._start_correction);if(f._end_correction)m.end_date=new Date(m.end_date-f._end_correction);m[f.y_property]=
f.y_unit[d].key;a.addEventNow(m,null,i)}});a.attachEvent("onBeforeDrag",function(){return!a._isRender("cell")});a.attachEvent("onEventChanged",function(a,d){d._timed=this.isOneDayEvent(d)});var Q=a._render_marked_timespan;a._render_marked_timespan=function(b,d,c,e,i){if(!a.config.display_marked_timespans)return[];if(a.matrix&&a.matrix[a._mode]){if(!a._isRender("cell")){var f=a._lame_copy({},a.matrix[a._mode]);f.round_position=!1;var m=[],g=[],j=[],n=b.sections?b.sections.units||b.sections.timeline:
null;if(c)j=[d],g=[c];else{var k=f.order;if(n)k.hasOwnProperty(n)&&(g.push(n),j.push(f._scales[n]));else for(var r in k)k.hasOwnProperty(r)&&(g.push(r),j.push(f._scales[r]))}var e=e?new Date(e):a._min_date,i=i?new Date(i):a._max_date,h=[];if(b.days>6){var q=new Date(b.days);a.date.date_part(new Date(e))<=+q&&+i>=+q&&h.push(q)}else h.push.apply(h,a._get_dates_by_index(b.days));for(var o=b.zones,p=a._get_css_classes_by_config(b),l=0;l<g.length;l++)for(var d=j[l],c=g[l],s=0;s<h.length;s++)for(var t=
h[s],u=0;u<o.length;u+=2){var v=o[u],C=o[u+1],w=new Date(+t+v*6E4),D=new Date(+t+C*6E4);if(e<D&&i>w){var z=a._get_block_by_config(b);z.className=p;var A=y({start_date:w},!1,f)-1,x=y({start_date:D},!1,f)-1,E=Math.max(1,x-A-1),F=f._section_height[c]-1;z.style.cssText="height: "+F+"px; left: "+A+"px; width: "+E+"px; top: 0;";d.insertBefore(z,d.firstChild);m.push(z)}}return m}}else return Q.apply(a,[b,d,c])};var R=a._append_mark_now;a._append_mark_now=function(b,d){if(a.matrix&&a.matrix[a._mode]){var c=
a._currentDate(),e=a._get_zone_minutes(c),i={days:+a.date.date_part(c),zones:[e,e+1],css:"dhx_matrix_now_time",type:"dhx_now_time"};return a._render_marked_timespan(i)}else return R.apply(a,[b,d])};a.attachEvent("onScaleAdd",function(b,d){var c=a._marked_timespans;if(c&&a.matrix&&a.matrix[a._mode])for(var e=a._mode,i=a._min_date,f=a._max_date,m=c.global,g=a.date.date_part(new Date(i));g<f;g=a.date.add(g,1,"day")){var j=+g,n=g.getDay(),k=[],r=m[j]||m[n];k.push.apply(k,a._get_configs_to_render(r));
if(c[e]&&c[e][d]){var h=[],q=a._get_types_to_render(c[e][d][n],c[e][d][j]);h.push.apply(h,a._get_configs_to_render(q));h.length&&(k=h)}for(var o=0;o<k.length;o++){var p=k[o],l=p.days;l<7?(l=j,a._render_marked_timespan(p,b,d,g,a.date.add(g,1,"day")),l=n):a._render_marked_timespan(p,b,d,g,a.date.add(g,1,"day"))}}});a._get_date_index=function(a,d){for(var c=0,e=a._trace_x;c<e.length-1&&+d>=+e[c+1];)c++;return c}})()});
