/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){a.config.limit_start=null;a.config.limit_end=null;a.config.limit_view=!1;a.config.check_limits=!0;a.config.mark_now=!0;a.config.display_marked_timespans=!0;(a._temp_limit_scope=function(){function B(d,b,c,e,f){function g(b,a,d,c){var e=[];if(b&&b[a])for(var f=b[a],g=i(d,c,f),j=0;j<g.length;j++)e=h._add_timespan_zones(e,g[j].zones);return e}function i(b,a,d){var c=d[a]&&d[a][f]?d[a][f]:d[b]&&d[b][f]?d[b][f]:[];return c}var h=a,j=[],k={_props:"map_to",matrix:"y_property"},
m;for(m in k){var o=k[m];if(h[m])for(var n in h[m]){var p=h[m][n],l=p[o];d[l]&&(j=h._add_timespan_zones(j,g(b[n],d[l],c,e)))}}return j=h._add_timespan_zones(j,g(b,"global",c,e))}var v=null,u="dhx_time_block",w="default",C=function(a,b,c){b instanceof Date&&c instanceof Date?(a.start_date=b,a.end_date=c):(a.days=b,a.zones=c);return a},y=function(a,b,c){var e=typeof a=="object"?a:{days:a};e.type=u;e.css="";if(b){if(c)e.sections=c;e=C(e,a,b)}return e};a.blockTime=function(d,b,c){var e=y(d,b,c);return a.addMarkedTimespan(e)};
a.unblockTime=function(d,b,c){var b=b||"fullday",e=y(d,b,c);return a.deleteMarkedTimespan(e)};a.attachEvent("onBeforeViewChange",function(d,b,c,e){e=e||b;c=c||d;return a.config.limit_view&&(e.valueOf()>a.config.limit_end.valueOf()||this.date.add(e,1,c)<=a.config.limit_start.valueOf())?(setTimeout(function(){a.setCurrentView(a._date,c)},1),!1):!0});a.checkInMarkedTimespan=function(d,b,c){for(var b=b||w,e=!0,f=new Date(d.start_date.valueOf()),g=a.date.add(f,1,"day"),i=a._marked_timespans;f<d.end_date;f=
a.date.date_part(g),g=a.date.add(f,1,"day")){var h=+a.date.date_part(new Date(f)),j=f.getDay(),k=B(d,i,j,h,b);if(k)for(var m=0;m<k.length;m+=2){var o=a._get_zone_minutes(f),n=d.end_date>g||d.end_date.getDate()!=f.getDate()?1440:a._get_zone_minutes(d.end_date),p=k[m],l=k[m+1];if(p<n&&l>o&&(e=c=="function"?c(d,o,n,p,l):!1,!e))break}}return!e};var t=a.checkLimitViolation=function(d){if(!d)return!0;if(!a.config.check_limits)return!0;var b=a,c=b.config,e=[];if(d.rec_type)for(var f=a.getRecDates(d),g=0;g<
f.length;g++){var i=a._copy_event(d);a._lame_copy(i,f[g]);e.push(i)}else e=[d];for(var h=!0,j=0;j<e.length;j++){var k=!0,i=e[j];i._timed=a.isOneDayEvent(i);(k=c.limit_start&&c.limit_end?i.start_date.valueOf()>=c.limit_start.valueOf()&&i.end_date.valueOf()<=c.limit_end.valueOf():!0)&&(k=!a.checkInMarkedTimespan(i,u,function(a,d,c,e,f){var g=!0;if(d<=f&&d>=e){if(f==1440||c<f)g=!1;a._timed&&b._drag_id&&b._drag_mode=="new-size"?(a.start_date.setHours(0),a.start_date.setMinutes(f)):g=!1}if(c>=e&&c<f||
d<e&&c>f)a._timed&&b._drag_id&&b._drag_mode=="new-size"?(a.end_date.setHours(0),a.end_date.setMinutes(e)):g=!1;return g}));k||(k=b.checkEvent("onLimitViolation")?b.callEvent("onLimitViolation",[i.id,i]):k);h=h&&k}if(!h)b._drag_id=null,b._drag_mode=null;return h};a.attachEvent("onMouseDown",function(a){return a!=u});a.attachEvent("onBeforeDrag",function(d){return!d?!0:t(a.getEvent(d))});a.attachEvent("onClick",function(d){return t(a.getEvent(d))});a.attachEvent("onBeforeLightbox",function(d){var b=
a.getEvent(d);v=[b.start_date,b.end_date];return t(b)});a.attachEvent("onEventSave",function(d,b){if(!b.start_date||!b.end_date){var c=a.getEvent(d);b.start_date=new Date(c.start_date);b.end_date=new Date(c.end_date)}if(b.rec_type){var e=a._lame_clone(b);a._roll_back_dates(e);return t(e)}return t(b)});a.attachEvent("onEventAdded",function(d){if(!d)return!0;var b=a.getEvent(d);if(!t(b)&&a.config.limit_start&&a.config.limit_end){if(b.start_date<a.config.limit_start)b.start_date=new Date(a.config.limit_start);
if(b.start_date.valueOf()>=a.config.limit_end.valueOf())b.start_date=this.date.add(a.config.limit_end,-1,"day");if(b.end_date<a.config.limit_start)b.end_date=new Date(a.config.limit_start);if(b.end_date.valueOf()>=a.config.limit_end.valueOf())b.end_date=this.date.add(a.config.limit_end,-1,"day");if(b.start_date.valueOf()>=b.end_date.valueOf())b.end_date=this.date.add(b.start_date,this.config.event_duration||this.config.time_step,"minute");b._timed=this.isOneDayEvent(b)}return!0});a.attachEvent("onEventChanged",
function(d){if(!d)return!0;var b=a.getEvent(d);if(!t(b)){if(!v)return!1;b.start_date=v[0];b.end_date=v[1];b._timed=this.isOneDayEvent(b)}return!0});a.attachEvent("onBeforeEventChanged",function(a){return t(a)});a.attachEvent("onBeforeEventCreated",function(d){var b=a.getActionData(d).date,c={_timed:!0,start_date:b,end_date:a.date.add(b,a.config.time_step,"minute")};return t(c)});a.attachEvent("onViewChange",function(){a._mark_now()});a.attachEvent("onSchedulerResize",function(){window.setTimeout(function(){a._mark_now()},
1);return!0});a.attachEvent("onTemplatesReady",function(){a._mark_now_timer=window.setInterval(function(){a._mark_now()},6E4)});a._mark_now=function(d){var b="dhx_now_time";this._els[b]||(this._els[b]=[]);var c=a._currentDate(),e=this.config;a._remove_mark_now();if(!d&&e.mark_now&&c<this._max_date&&c>this._min_date&&c.getHours()>=e.first_hour&&c.getHours()<e.last_hour){var f=this.locate_holder_day(c);this._els[b]=a._append_mark_now(f,c)}};a._append_mark_now=function(d,b){var c="dhx_now_time",e=a._get_zone_minutes(b),
f={zones:[e,e+1],css:c,type:c};if(this._table_view){if(this._mode=="month")return f.days=+a.date.date_part(b),a._render_marked_timespan(f,null,null)}else if(this._props&&this._props[this._mode]){for(var g=this._els.dhx_cal_data[0].childNodes,i=[],h=0;h<g.length-1;h++){var j=d+h;f.days=j;var k=a._render_marked_timespan(f,null,j)[0];i.push(k)}return i}else return f.days=d,a._render_marked_timespan(f,null,d)};a._remove_mark_now=function(){for(var a="dhx_now_time",b=this._els[a],c=0;c<b.length;c++){var e=
b[c],f=e.parentNode;f&&f.removeChild(e)}this._els[a]=[]};a._marked_timespans={global:{}};a._get_zone_minutes=function(a){return a.getHours()*60+a.getMinutes()};a._prepare_timespan_options=function(d){var b=[],c=[];if(d.days=="fullweek")d.days=[0,1,2,3,4,5,6];if(d.days instanceof Array){for(var e=d.days.slice(),f=0;f<e.length;f++){var g=a._lame_clone(d);g.days=e[f];b.push.apply(b,a._prepare_timespan_options(g))}return b}if(!d||!(d.start_date&&d.end_date&&d.end_date>d.start_date||d.days!==void 0&&d.zones))return b;
var i=0,h=1440;if(d.zones=="fullday")d.zones=[i,h];if(d.zones&&d.invert_zones)d.zones=a.invertZones(d.zones);d.id=a.uid();d.css=d.css||"";d.type=d.type||w;var j=d.sections;if(j)for(var k in j){if(j.hasOwnProperty(k)){var m=j[k];m instanceof Array||(m=[m]);for(f=0;f<m.length;f++){var o=a._lame_copy({},d);o.sections={};o.sections[k]=m[f];c.push(o)}}}else c.push(d);for(var n=0;n<c.length;n++){var p=c[n],l=p.start_date,q=p.end_date;if(l&&q)for(var r=a.date.date_part(new Date(l)),x=a.date.add(r,1,"day");r<
q;){o=a._lame_copy({},p);delete o.start_date;delete o.end_date;o.days=r.valueOf();var s=l>r?a._get_zone_minutes(l):i,t=q>x||q.getDate()!=r.getDate()?h:a._get_zone_minutes(q);o.zones=[s,t];b.push(o);r=x;x=a.date.add(x,1,"day")}else{if(p.days instanceof Date)p.days=a.date.date_part(p.days).valueOf();p.zones=d.zones.slice();b.push(p)}}return b};a._get_dates_by_index=function(d,b,c){for(var e=[],b=a.date.date_part(new Date(b||a._min_date)),c=new Date(c||a._max_date),f=b.getDay(),g=d-f>=0?d-f:7-b.getDay()+
d,i=a.date.add(b,g,"day");i<c;i=a.date.add(i,1,"week"))e.push(i);return e};a._get_css_classes_by_config=function(a){var b=[];a.type==u&&(b.push(u),a.css&&b.push(u+"_reset"));b.push("dhx_marked_timespan",a.css);return b.join(" ")};a._get_block_by_config=function(a){var b=document.createElement("DIV");if(a.html)typeof a.html=="string"?b.innerHTML=a.html:b.appendChild(a.html);return b};a._render_marked_timespan=function(d,b,c){var e=[],f=a.config,g=this._min_date,i=this._max_date,h=!1;if(!f.display_marked_timespans)return e;
if(!c&&c!==0){if(d.days<7)c=d.days;else{var j=new Date(d.days),h=+j;if(!(+i>=+j&&+g<=+j))return e;c=j.getDay()}var k=g.getDay();k>c?c=7-(k-c):c-=k}var m=d.zones,o=a._get_css_classes_by_config(d);if(a._table_view&&a._mode=="month"){var n=[],p=[];if(b)n.push(b),p.push(c);else for(var p=h?[h]:a._get_dates_by_index(c),l=0;l<p.length;l++)n.push(this._scales[p[l]]);for(l=0;l<n.length;l++)for(var b=n[l],c=p[l],q=0;q<m.length;q+=2){var r=m[l],t=m[l+1];if(t<=r)return[];var s=a._get_block_by_config(d);s.className=
o;var u=b.offsetHeight-1,v=b.offsetWidth-1,w=Math.floor((this._correct_shift(c,1)-g.valueOf())/(864E5*this._cols.length)),y=this.locate_holder_day(c,!1)%this._cols.length,B=this._colsS[y],C=this._colsS.heights[w]+(this._colsS.height?this.xy.month_scale_height+2:2)-1;s.style.top=C+"px";s.style.lineHeight=s.style.height=u+"px";s.style.left=B+Math.round(r/1440*v)+"px";s.style.width=Math.round((t-r)/1440*v)+"px";b.appendChild(s);e.push(s)}}else{var z=c;if(this._props&&this._props[this._mode]&&d.sections&&
d.sections[this._mode]){var A=this._props[this._mode],z=A.order[d.sections[this._mode]];A.size&&z>A.position+A.size&&(z=0)}b=b?b:a.locate_holder(z);for(l=0;l<m.length;l+=2){r=Math.max(m[l],f.first_hour*60);t=Math.min(m[l+1],f.last_hour*60);if(t<=r)if(l+2<m.length)continue;else return[];s=a._get_block_by_config(d);s.className=o;var E=this.config.hour_size_px*24+1,D=36E5;s.style.top=Math.round((r*6E4-this.config.first_hour*D)*this.config.hour_size_px/D)%E+"px";s.style.lineHeight=s.style.height=Math.max(Math.round((t-
r)*6E4*this.config.hour_size_px/D)%E,1)+"px";b.appendChild(s);e.push(s)}}return e};a.markTimespan=function(d){var b=a._prepare_timespan_options(d);if(b.length){for(var c=[],e=0;e<b.length;e++){var f=b[e],g=a._render_marked_timespan(f,null,null);g.length&&c.push.apply(c,g)}return c}};a.unmarkTimespan=function(a){if(a)for(var b=0;b<a.length;b++){var c=a[b];c.parentNode&&c.parentNode.removeChild(c)}};a._marked_timespans_ids={};a.addMarkedTimespan=function(d){var b=a._prepare_timespan_options(d),c="global";
if(b.length){var e=b[0].id,f=a._marked_timespans,g=a._marked_timespans_ids;g[e]||(g[e]=[]);for(var i=0;i<b.length;i++){var h=b[i],j=h.days,k=h.zones,m=h.css,o=h.sections,n=h.type;h.id=e;if(o)for(var p in o){if(o.hasOwnProperty(p)){f[p]||(f[p]={});var l=o[p],q=f[p];q[l]||(q[l]={});q[l][j]||(q[l][j]={});if(!q[l][j][n]){q[l][j][n]=[];if(!a._marked_timespans_types)a._marked_timespans_types={};a._marked_timespans_types[n]||(a._marked_timespans_types[n]=!0)}var r=q[l][j][n];h._array=r;r.push(h);g[e].push(h)}}else{f[c][j]||
(f[c][j]={});f[c][j][n]||(f[c][j][n]=[]);if(!a._marked_timespans_types)a._marked_timespans_types={};a._marked_timespans_types[n]||(a._marked_timespans_types[n]=!0);r=f[c][j][n];h._array=r;r.push(h);g[e].push(h)}}return e}};a._add_timespan_zones=function(a,b){var c=a.slice(),b=b.slice();if(!c.length)return b;for(var e=0;e<c.length;e+=2)for(var f=c[e],g=c[e+1],i=e+2==c.length,h=0;h<b.length;h+=2){var j=b[h],k=b[h+1];if(k>g&&j<=g||j<f&&k>=f)c[e]=Math.min(f,j),c[e+1]=Math.max(g,k),e-=2;else{if(!i)continue;
var m=f>j?0:2;c.splice(e+m,0,j,k)}b.splice(h--,2);break}return c};a._subtract_timespan_zones=function(a,b){for(var c=a.slice(),e=0;e<c.length;e+=2)for(var f=c[e],g=c[e+1],i=0;i<b.length;i+=2){var h=b[i],j=b[i+1];if(j>f&&h<g){var k=!1;f>=h&&g<=j&&c.splice(e,2);f<h&&(c.splice(e,2,f,h),k=!0);g>j&&c.splice(k?e+2:e,k?0:2,j,g);e-=2;break}}return c};a.invertZones=function(d){return a._subtract_timespan_zones([0,1440],d.slice())};a._delete_marked_timespan_by_id=function(d){var b=a._marked_timespans_ids[d];
if(b)for(var c=0;c<b.length;c++)for(var e=b[c],f=e._array,g=0;g<f.length;g++)if(f[g]==e){f.splice(g,1);break}};a._delete_marked_timespan_by_config=function(d){var b=a._marked_timespans,c=d.sections,e=d.days,f=d.type||w,g=[];if(c)for(var i in c){if(c.hasOwnProperty(i)&&b[i]){var h=c[i];b[i][h]&&b[i][h][e]&&b[i][h][e][f]&&(g=b[i][h][e][f])}}else b.global[e]&&b.global[e][f]&&(g=b.global[e][f]);for(var j=0;j<g.length;j++){var k=g[j],m=a._subtract_timespan_zones(k.zones,d.zones);if(m.length)k.zones=m;
else{g.splice(j,1);j--;for(var o=a._marked_timespans_ids[k.id],n=0;n<o.length;n++)if(o[n]==k){o.splice(n,1);break}}}};a.deleteMarkedTimespan=function(d){if(!arguments.length)a._marked_timespans={global:{}},a._marked_timespans_ids={},a._marked_timespans_types={};if(typeof d!="object")a._delete_marked_timespan_by_id(d);else{if(!d.start_date||!d.end_date){if(!d.days)d.days="fullweek";if(!d.zones)d.zones="fullday"}var b=[];if(d.type)b.push(d.type);else for(var c in a._marked_timespans_types)b.push(c);
for(var e=a._prepare_timespan_options(d),f=0;f<e.length;f++)for(var g=e[f],i=0;i<b.length;i++){var h=a._lame_clone(g);h.type=b[i];a._delete_marked_timespan_by_config(h)}}};a._get_types_to_render=function(a,b){var c=a?a:{},e;for(e in b||{})b.hasOwnProperty(e)&&(c[e]=b[e]);return c};a._get_configs_to_render=function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push.apply(b,a[c]);return b};a.attachEvent("onScaleAdd",function(d,b){if(!(a._table_view&&a._mode!="month")){var c=b.getDay(),e=b.valueOf(),
f=this._mode,g=a._marked_timespans,i=[];if(this._props&&this._props[f]){var h=this._props[f],j=h.options,k=a._get_unit_index(h,b),m=j[k],b=a.date.date_part(new Date(this._date)),c=b.getDay(),e=b.valueOf();if(g[f]&&g[f][m.key]){var o=g[f][m.key],n=a._get_types_to_render(o[c],o[e]);i.push.apply(i,a._get_configs_to_render(n))}}var p=g.global,l=p[e]||p[c];i.push.apply(i,a._get_configs_to_render(l));for(var q=0;q<i.length;q++)a._render_marked_timespan(i[q],d,b)}})})()});
