/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(a){(function(){a._grid={sort_rules:{"int":function(a,d,b){return b(a)*1<b(d)*1?1:-1},str:function(a,d,b){return b(a)<b(d)?1:-1},date:function(a,d,b){return new Date(b(a))<new Date(b(d))?1:-1}},_getObjName:function(a){return"grid_"+a},_getViewName:function(a){return a.replace(/^grid_/,"")}}})();a.createGridView=function(c){function d(a){return!(a!==void 0&&(a*1!=a||a<0))}var b=c.name||"grid",e=a._grid._getObjName(b);a.config[b+"_start"]=c.from||new Date(0);a.config[b+"_end"]=
c.to||new Date(9999,1,1);a[e]=c;a[e].defPadding=8;a[e].columns=a[e].fields;delete a[e].fields;for(var f=a[e].columns,g=0;g<f.length;g++){if(d(f[g].width))f[g].initialWidth=f[g].width;d(f[g].paddingLeft)||delete f[g].paddingLeft;d(f[g].paddingRight)||delete f[g].paddingRight}a[e].select=c.select===void 0?!0:c.select;a.locale.labels[b+"_tab"]===void 0&&(a.locale.labels[b+"_tab"]=a[e].label||a.locale.labels.grid_tab);a[e]._selected_divs=[];a.date[b+"_start"]=function(a){return a};a.date["add_"+b]=function(a,
b){var c=new Date(a);c.setMonth(c.getMonth()+b);return c};a.templates[b+"_date"]=function(b,c){return a.templates.day_date(b)+" - "+a.templates.day_date(c)};a.templates[b+"_full_date"]=function(c,e,d){return a.isOneDayEvent(d)?this[b+"_single_date"](c):a.templates.day_date(c)+" &ndash; "+a.templates.day_date(e)};a.templates[b+"_single_date"]=function(b){return a.templates.day_date(b)+" "+this.event_date(b)};a.templates[b+"_field"]=function(a,b){return b[a]};a.attachEvent("onTemplatesReady",function(){a.attachEvent("onDblClick",
function(c){return this._mode==b?(a._click.buttons.details(c),!1):!0});a.attachEvent("onClick",function(c,d){return this._mode==b&&a[e].select?(a._grid.unselectEvent("",b),a._grid.selectEvent(c,b,d),!1):!0});a.attachEvent("onSchedulerResize",function(){return this._mode==b?(this[b+"_view"](!0),window.setTimeout(function(){a.callEvent("onAfterSchedulerResize",[])},1),!1):!0});var c=a.render_data;a.render_data=function(d){if(this._mode==b)a._grid._fill_grid_tab(e);else return c.apply(this,arguments)};
var d=a.render_view_data;a.render_view_data=function(){if(this._mode==b)a._grid._gridScrollTop=a._els.dhx_cal_data[0].childNodes[0].scrollTop,a._els.dhx_cal_data[0].childNodes[0].scrollTop=0;a._els.dhx_cal_data[0].style.overflowY="auto";return d.apply(this,arguments)}});a[b+"_view"]=function(c){c?(a._min_date=a[e].paging?a.date[b+"_start"](new Date(a._date)):a.config[b+"_start"],a._max_date=a[e].paging?a.date.add(a._min_date,1,b):a.config[b+"_end"],a._grid.set_full_view(e),a._els.dhx_cal_date[0].innerHTML=
a._min_date>new Date(0)&&a._max_date<new Date(9999,1,1)?a.templates[b+"_date"](a._min_date,a._max_date):"",a._grid._fill_grid_tab(e),a._gridView=e):(a._grid._sort_marker=null,delete a._gridView,a._rendered=[],a[e]._selected_divs=[])}};a.dblclick_dhx_grid_area=function(){!this.config.readonly&&this.config.dblclick_create&&this.addEventNow()};if(a._click.dhx_cal_header)a._old_header_click=a._click.dhx_cal_header;a._click.dhx_cal_header=function(c){if(a._gridView){var d=c||window.event,b=a._grid.get_sort_params(d,
a._gridView);a._grid.draw_sort_marker(d.originalTarget||d.srcElement,b.dir);a.clear_view();a._grid._fill_grid_tab(a._gridView,b)}else if(a._old_header_click)return a._old_header_click.apply(this,arguments)};a._grid.selectEvent=function(c,d,b){if(a.callEvent("onBeforeRowSelect",[c,b])){var e=a._grid._getObjName(d);a.for_rendered(c,function(b){b.className+=" dhx_grid_event_selected";a[e]._selected_divs.push(b)});a._select_id=c}};a._grid._unselectDiv=function(a){a.className=a.className.replace(/ dhx_grid_event_selected/,
"")};a._grid.unselectEvent=function(c,d){var b=a._grid._getObjName(d);if(b&&a[b]._selected_divs)if(c)for(e=0;e<a[b]._selected_divs.length;e++){if(a[b]._selected_divs[e].getAttribute("event_id")==c){a._grid._unselectDiv(a[b]._selected_divs[e]);a[b]._selected_divs.slice(e,1);break}}else{for(var e=0;e<a[b]._selected_divs.length;e++)a._grid._unselectDiv(a[b]._selected_divs[e]);a[b]._selected_divs=[]}};a._grid.get_sort_params=function(c,d){var b=c.originalTarget||c.srcElement;if(b.className=="dhx_grid_view_sort")b=
b.parentNode;for(var e=!b.className||b.className.indexOf("dhx_grid_sort_asc")==-1?"asc":"desc",f=0,g=0;g<b.parentNode.childNodes.length;g++)if(b.parentNode.childNodes[g]==b){f=g;break}var j=null;if(a[d].columns[f].template)var h=a[d].columns[f].template,j=function(a){return h(a.start_date,a.end_date,a)};else{var l=a[d].columns[f].id;l=="date"&&(l="start_date");j=function(a){return a[l]}}var i=a[d].columns[f].sort;typeof i!="function"&&(i=a._grid.sort_rules[i]||a._grid.sort_rules.str);return{dir:e,
value:j,rule:i}};a._grid.draw_sort_marker=function(c,d){if(c.className=="dhx_grid_view_sort")c=c.parentNode;if(a._grid._sort_marker)a._grid._sort_marker.className=a._grid._sort_marker.className.replace(/( )?dhx_grid_sort_(asc|desc)/,""),a._grid._sort_marker.removeChild(a._grid._sort_marker.lastChild);c.className+=" dhx_grid_sort_"+d;a._grid._sort_marker=c;var b="<div class='dhx_grid_view_sort' style='left:"+(+c.style.width.replace("px","")-15+c.offsetLeft)+"px'>&nbsp;</div>";c.innerHTML+=b};a._grid.sort_grid=
function(c){var c=c||{dir:"desc",value:function(a){return a.start_date},rule:a._grid.sort_rules.date},d=a.get_visible_events();c.dir=="desc"?d.sort(function(a,d){return c.rule(a,d,c.value)}):d.sort(function(a,d){return-c.rule(a,d,c.value)});return d};a._grid.set_full_view=function(c){if(c){var d=a.locale.labels,b=a._grid._print_grid_header(c);a._els.dhx_cal_header[0].innerHTML=b;a._table_view=!0;a.set_sizes()}};a._grid._calcPadding=function(c,d){var b=(c.paddingLeft!==void 0?1*c.paddingLeft:a[d].defPadding)+
(c.paddingRight!==void 0?1*c.paddingRight:a[d].defPadding);return b};a._grid._getStyles=function(a,d){for(var b=[],e="",f=0;d[f];f++)switch(e=d[f]+":",d[f]){case "text-align":a.align&&b.push(e+a.align);break;case "vertical-align":a.valign&&b.push(e+a.valign);break;case "padding-left":a.paddingLeft!=void 0&&b.push(e+(a.paddingLeft||"0")+"px");break;case "padding-right":a.paddingRight!=void 0&&b.push(e+(a.paddingRight||"0")+"px")}return b};a._grid._fill_grid_tab=function(c,d){for(var b=a._date,e=a._grid.sort_grid(d),
f=a[c].columns,g="<div>",j=-2,h=0;h<f.length;h++){var l=a._grid._calcPadding(f[h],c);j+=f[h].width+l;h<f.length-1&&(g+="<div class='dhx_grid_v_border' style='left:"+j+"px'></div>")}g+="</div>";g+="<div class='dhx_grid_area'><table>";for(h=0;h<e.length;h++)g+=a._grid._print_event_row(e[h],c);g+="</table></div>";a._els.dhx_cal_data[0].innerHTML=g;a._els.dhx_cal_data[0].scrollTop=a._grid._gridScrollTop||0;var i=a._els.dhx_cal_data[0].getElementsByTagName("tr");a._rendered=[];for(h=0;h<i.length;h++)a._rendered[h]=
i[h]};a._grid._print_event_row=function(c,d){var b=[];c.color&&b.push("background:"+c.color);c.textColor&&b.push("color:"+c.textColor);c._text_style&&b.push(c._text_style);a[d].rowHeight&&b.push("height:"+a[d].rowHeight+"px");var e="";b.length&&(e="style='"+b.join(";")+"'");for(var f=a[d].columns,g=a.templates.event_class(c.start_date,c.end_date,c),j="<tr class='dhx_grid_event"+(g?" "+g:"")+"' event_id='"+c.id+"' "+e+">",h=a._grid._getViewName(d),l=["text-align","vertical-align","padding-left","padding-right"],
i=0;i<f.length;i++){var k;k=f[i].template?f[i].template(c.start_date,c.end_date,c):f[i].id=="date"?a.templates[h+"_full_date"](c.start_date,c.end_date,c):f[i].id=="start_date"||f[i].id=="end_date"?a.templates[h+"_single_date"](c[f[i].id]):a.templates[h+"_field"](f[i].id,c);var m=a._grid._getStyles(f[i],l),n=f[i].css?' class="'+f[i].css+'"':"";j+="<td style='width:"+f[i].width+"px;"+m.join(";")+"' "+n+">"+k+"</td>"}j+="<td class='dhx_grid_dummy'></td></tr>";return j};a._grid._print_grid_header=function(c){for(var d=
"<div class='dhx_grid_line'>",b=a[c].columns,e=[],f=b.length,g=a._obj.clientWidth-2*b.length-20,j=0;j<b.length;j++){var h=b[j].initialWidth*1;!isNaN(h)&&b[j].initialWidth!=""&&b[j].initialWidth!=null&&typeof b[j].initialWidth!="boolean"?(f--,g-=h,e[j]=h):e[j]=null}for(var l=Math.floor(g/f),i=["text-align","padding-left","padding-right"],k=0;k<b.length;k++){var m=!e[k]?l:e[k];b[k].width=m-a._grid._calcPadding(b[k],c);var n=a._grid._getStyles(b[k],i);d+="<div style='width:"+(b[k].width-1)+"px;"+n.join(";")+
"'>"+(b[k].label===void 0?b[k].id:b[k].label)+"</div>"}d+="</div>";return d}});
