/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(c){(function(){function h(a){return a.replace(G,"\n").replace(H,"")}function A(a,c){a=parseFloat(a);c=parseFloat(c);isNaN(c)||(a-=c);var b=r(a),a=a-b.width+b.cols*i;return isNaN(a)?"auto":100*a/i}function D(a,c,b){a=parseFloat(a);c=parseFloat(c);!isNaN(c)&&b&&(a-=c);var e=r(a),a=a-e.width+e.cols*i;return isNaN(a)?"auto":100*a/(i-(!isNaN(c)?c:0))}function r(a){for(var f=0,b=c._els.dhx_cal_header[0].childNodes,e=b[1]?b[1].childNodes:b[0].childNodes,d=0;d<e.length;d++){var g=
e[d].style?e[d]:e[d].parentNode,j=parseFloat(g.style.width);if(a>j)a-=j+1,f+=j+1;else break}return{width:f,cols:d}}function B(a){a=parseFloat(a);return isNaN(a)?"auto":100*a/n}function m(a,c){return(window.getComputedStyle?window.getComputedStyle(a,null)[c]:a.currentStyle?a.currentStyle[c]:null)||""}function I(a,f){for(var b=parseInt(a.style.left,10),e=0;e<c._cols.length;e++)if(b-=c._cols[e],b<0)return e;return f}function J(a,f){for(var b=parseInt(a.style.top,10),e=0;e<c._colsS.heights.length;e++)if(c._colsS.heights[e]>
b)return e;return f}function K(a){return a?"<"+a+">":""}function q(a){return a?"</"+a+">":""}function u(a,c,b,e){var d="<"+a+" profile='"+c+"'";b&&(d+=" header='"+b+"'");e&&(d+=" footer='"+e+"'");d+=">";return d}function v(){var a="",f=c._mode;c.matrix&&c.matrix[c._mode]&&(f=c.matrix[c._mode].render=="cell"?"matrix":"timeline");a+="<scale mode='"+f+"' today='"+c._els.dhx_cal_date[0].innerHTML+"'>";if(c._mode=="week_agenda")for(var b=c._els.dhx_cal_data[0].getElementsByTagName("DIV"),e=0;e<b.length;e++)b[e].className==
"dhx_wa_scale_bar"&&(a+="<column>"+h(b[e].innerHTML)+"</column>");else if(c._mode=="agenda"||c._mode=="map")b=c._els.dhx_cal_header[0].childNodes[0].childNodes,a+="<column>"+h(b[0].innerHTML)+"</column><column>"+h(b[1].innerHTML)+"</column>";else if(c._mode=="year"){b=c._els.dhx_cal_data[0].childNodes;for(e=0;e<b.length;e++)a+="<month label='"+h(b[e].childNodes[0].innerHTML)+"'>",a+=w(b[e].childNodes[1].childNodes),a+=s(b[e].childNodes[2]),a+="</month>"}else{a+="<x>";b=c._els.dhx_cal_header[0].childNodes;
a+=w(b);a+="</x>";var d=c._els.dhx_cal_data[0];if(c.matrix&&c.matrix[c._mode]){a+="<y>";for(e=0;e<d.firstChild.rows.length;e++){var g=d.firstChild.rows[e];a+="<row><![CDATA["+h(g.cells[0].innerHTML)+"]]\></row>"}a+="</y>";n=d.firstChild.rows[0].cells[0].offsetHeight}else if(d.firstChild.tagName=="TABLE")a+=s(d);else{for(d=d.childNodes[d.childNodes.length-1];d.className.indexOf("dhx_scale_holder")==-1;)d=d.previousSibling;d=d.childNodes;a+="<y>";for(e=0;e<d.length;e++)a+="\n<row><![CDATA["+h(d[e].innerHTML)+
"]]\></row>";a+="</y>";n=d[0].offsetHeight}}a+="</scale>";return a}function s(a){for(var c="",b=a.firstChild.rows,e=0;e<b.length;e++){for(var d=[],g=0;g<b[e].cells.length;g++)d.push(b[e].cells[g].firstChild.innerHTML);c+="\n<row height='"+a.firstChild.rows[e].cells[0].offsetHeight+"'><![CDATA["+h(d.join("|"))+"]]\></row>";n=a.firstChild.rows[0].cells[0].offsetHeight}return c}function w(a){var f="";if(c.matrix&&c.matrix[c._mode]){if(c.matrix[c._mode].second_scale)var b=a[1].childNodes;a=a[0].childNodes}for(var e=
0;e<a.length;e++)f+="\n<column><![CDATA["+h(a[e].innerHTML)+"]]\></column>";i=a[0].offsetWidth;if(b)for(var d=0,g=a[0].offsetWidth,j=1,e=0;e<b.length;e++)f+="\n<column second_scale='"+j+"'><![CDATA["+h(b[e].innerHTML)+"]]\></column>",d+=b[e].offsetWidth,d>=g&&(g+=a[j]?a[j].offsetWidth:0,j++),i=b[0].offsetWidth;return f}function x(a){var f="",b=c._rendered,e=c.matrix&&c.matrix[c._mode];if(c._mode=="agenda"||c._mode=="map")for(var d=0;d<b.length;d++)f+="<event><head><![CDATA["+h(b[d].childNodes[0].innerHTML)+
"]]\></head><body><![CDATA["+h(b[d].childNodes[2].innerHTML)+"]]\></body></event>";else if(c._mode=="week_agenda")for(d=0;d<b.length;d++)f+="<event day='"+b[d].parentNode.getAttribute("day")+"'><body>"+h(b[d].innerHTML)+"</body></event>";else if(c._mode=="year"){b=c.get_visible_events();for(d=0;d<b.length;d++){var g=b[d].start_date;if(g.valueOf()<c._min_date.valueOf())g=c._min_date;for(;g<b[d].end_date;){var j=g.getMonth()+12*(g.getFullYear()-c._min_date.getFullYear())-c.week_starts._month,o=c.week_starts[j]+
g.getDate()-1,p=a?m(c._get_year_cell(g),"color"):"",k=a?m(c._get_year_cell(g),"backgroundColor"):"";f+="<event day='"+o%7+"' week='"+Math.floor(o/7)+"' month='"+j+"' backgroundColor='"+k+"' color='"+p+"'></event>";g=c.date.add(g,1,"day");if(g.valueOf()>=c._max_date.valueOf())break}}}else if(e&&e.render=="cell"){b=c._els.dhx_cal_data[0].getElementsByTagName("TD");for(d=0;d<b.length;d++)p=a?m(b[d],"color"):"",k=a?m(b[d],"backgroundColor"):"",f+="\n<event><body backgroundColor='"+k+"' color='"+p+"'><![CDATA["+
h(b[d].innerHTML)+"]]\></body></event>"}else for(d=0;d<b.length;d++){var l,i;if(c.matrix&&c.matrix[c._mode])l=A(b[d].style.left),i=A(b[d].offsetWidth)-1;else{var q=c.config.use_select_menu_space?0:26;l=D(b[d].style.left,q,!0);i=D(b[d].style.width,q)-1}if(!isNaN(i*1)){var t=B(b[d].style.top),r=B(b[d].style.height),C=b[d].className.split(" ")[0].replace("dhx_cal_","");if(C!=="dhx_tooltip_line"){var y=c.getEvent(b[d].getAttribute("event_id"));if(y){var o=y._sday,z=y._sweek,u=y._length||0;if(c._mode==
"month")r=parseInt(b[d].offsetHeight,10),t=parseInt(b[d].style.top,10)-22,o=I(b[d],o),z=J(b[d],z);else if(c.matrix&&c.matrix[c._mode]){var o=0,v=b[d].parentNode.parentNode.parentNode,z=v.rowIndex,w=n;n=b[d].parentNode.offsetHeight;t=B(b[d].style.top);t-=t*0.2;n=w}else{if(b[d].parentNode==c._els.dhx_cal_data[0])continue;var s=c._els.dhx_cal_data[0].childNodes[0],x=parseFloat(s.className.indexOf("dhx_scale_holder")!=-1?s.style.left:0);l+=A(b[d].parentNode.style.left,x)}f+="\n<event week='"+z+"' day='"+
o+"' type='"+C+"' x='"+l+"' y='"+t+"' width='"+i+"' height='"+r+"' len='"+u+"'>";C=="event"?(f+="<header><![CDATA["+h(b[d].childNodes[1].innerHTML)+"]]\></header>",p=a?m(b[d].childNodes[2],"color"):"",k=a?m(b[d].childNodes[2],"backgroundColor"):"",f+="<body backgroundColor='"+k+"' color='"+p+"'><![CDATA["+h(b[d].childNodes[2].innerHTML)+"]]\></body>"):(p=a?m(b[d],"color"):"",k=a?m(b[d],"backgroundColor"):"",f+="<body backgroundColor='"+k+"' color='"+p+"'><![CDATA["+h(b[d].innerHTML)+"]]\></body>");
f+="</event>"}}}}return f}function E(a,c,b,e,d,g){var j=!1;e=="fullcolor"&&(j=!0,e="color");var e=e||"color",h="";if(a){for(var i=this._date,k=this._mode,h=u("pages",e,d,g),l=new Date(a);+l<+c;l=this.date.add(l,1,b))this.setCurrentView(l,b),h+=K("page")+v().replace("\u2013","-")+x(j)+q("page");h+=q("pages");this.setCurrentView(i,k)}else h=u("data",e,d,g)+v().replace("\u2013","-")+x(j)+q("data");return h}function L(a,f){var b=c.uid(),e=document.createElement("div");e.style.display="none";document.body.appendChild(e);
e.innerHTML='<form id="'+b+'" method="post" target="_blank" action="'+f+'" accept-charset="utf-8" enctype="application/x-www-form-urlencoded"><input type="hidden" name="mycoolxmlbody"/> </form>';document.getElementById(b).firstChild.value=encodeURIComponent(a);document.getElementById(b).submit();e.parentNode.removeChild(e)}function F(a,c,b,e,d,g,h){var i="",i=typeof d=="object"?M(d):E.apply(this,[a,c,b,d,g,h]);L(i,e)}function M(a){for(var c="<data>",b=0;b<a.length;b++)c+=a[b].source.getPDFData(a[b].start,
a[b].end,a[b].view,a[b].mode,a[b].header,a[b].footer);c+="</data>";return c}var i,n,H=RegExp("<[^>]*>","g"),G=RegExp("<br[^>]*>","g");c.getPDFData=E;c.toPDF=function(a,c,b,e){return F.apply(this,[null,null,null,a,c,b,e])};c.toPDFRange=function(a,f,b,e,d,g,h){typeof a=="string"&&(a=c.templates.api_date(a),f=c.templates.api_date(f));return F.apply(this,arguments)}})()});
