/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(b){(function(){var d=b.dhtmlXTooltip=b.tooltip={};d.config={className:"dhtmlXTooltip tooltip",timeout_to_display:50,timeout_to_hide:50,delta_x:15,delta_y:-20};d.tooltip=document.createElement("div");d.tooltip.className=d.config.className;d.show=function(c,l){if(!b.config.touch||b.config.touch_tooltip){var e=d,i=this.tooltip,a=i.style;e.tooltip.className=e.config.className;var h=this.position(c),j=c.target||c.srcElement;if(!this.isTooltip(j)){var f=h.x+(e.config.delta_x||
0),g=h.y-(e.config.delta_y||0);a.visibility="hidden";a.removeAttribute?(a.removeAttribute("right"),a.removeAttribute("bottom")):(a.removeProperty("right"),a.removeProperty("bottom"));a.left="0";a.top="0";this.tooltip.innerHTML=l;document.body.appendChild(this.tooltip);var k=this.tooltip.offsetWidth,m=this.tooltip.offsetHeight;document.body.offsetWidth-f-k<0?(a.removeAttribute?a.removeAttribute("left"):a.removeProperty("left"),a.right=document.body.offsetWidth-f+2*(e.config.delta_x||0)+"px"):a.left=
f<0?h.x+Math.abs(e.config.delta_x||0)+"px":f+"px";document.body.offsetHeight-g-m<0?(a.removeAttribute?a.removeAttribute("top"):a.removeProperty("top"),a.bottom=document.body.offsetHeight-g-2*(e.config.delta_y||0)+"px"):a.top=g<0?h.y+Math.abs(e.config.delta_y||0)+"px":g+"px";a.visibility="visible";b.callEvent("onTooltipDisplayed",[this.tooltip,this.tooltip.event_id])}}};d._clearTimeout=function(){this.tooltip._timeout_id&&window.clearTimeout(this.tooltip._timeout_id)};d.hide=function(){if(this.tooltip.parentNode){var c=
this.tooltip.event_id;this.tooltip.event_id=null;this.tooltip.parentNode.removeChild(this.tooltip);b.callEvent("onAfterTooltip",[c])}this._clearTimeout()};d.delay=function(c,b,e,d){this._clearTimeout();this.tooltip._timeout_id=setTimeout(function(){var a=c.apply(b,e);c=b=e=null;return a},d||this.config.timeout_to_display)};d.isTooltip=function(c){var b=!1;for(c.className.split(" ");c&&!b;)b=c.className==this.tooltip.className,c=c.parentNode;return b};d.position=function(c){c=c||window.event;if(c.pageX||
c.pageY)return{x:c.pageX,y:c.pageY};var b=window._isIE&&document.compatMode!="BackCompat"?document.documentElement:document.body;return{x:c.clientX+b.scrollLeft-b.clientLeft,y:c.clientY+b.scrollTop-b.clientTop}};b.attachEvent("onMouseMove",function(c,l){var e=window.event||l,i=e.target||e.srcElement,a=d,h=a.isTooltip(i),j=a.isTooltipTarget&&a.isTooltipTarget(i);if(c||h||j){var f;if(c||a.tooltip.event_id){var g=b.getEvent(c)||b.getEvent(a.tooltip.event_id);if(!g)return;a.tooltip.event_id=g.id;f=b.templates.tooltip_text(g.start_date,
g.end_date,g);if(!f)return a.hide()}j&&(f="");var k=void 0;_isIE&&(k=document.createEventObject(e));b.callEvent("onBeforeTooltip",[c])&&f&&a.delay(a.show,a,[k||e,f])}else a.delay(a.hide,a,[],a.config.timeout_to_hide)});b.attachEvent("onBeforeDrag",function(){d.hide();return!0});b.attachEvent("onEventDeleted",function(){d.hide();return!0});b.templates.tooltip_date_format=b.date.date_to_str("%Y-%m-%d %H:%i");b.templates.tooltip_text=function(c,d,e){return"<b>Event:</b> "+e.text+"<br/><b>Start date:</b> "+
b.templates.tooltip_date_format(c)+"<br/><b>End date:</b> "+b.templates.tooltip_date_format(d)}})()});
