/*
Copyright Dinamenta, UAB. http://www.dhtmlx.com
To use this component please contact sales@dhtmlx.com to obtain license
*/
Scheduler.plugin(function(j){j.initCustomLightbox=function(c,a,f){function k(){if(!a._lightbox){var b=a._getLightbox(),g=b.childNodes[1];b.className.indexOf("dhx_cal_light_wide")>=0?g.lastChild.firstChild.style.display="none":g.firstChild.style.display="none";g.style.height=g.style.height.replace("px","")-25+"px";b.style.height=b.style.height.replace("px","")-50+"px";b.style.width=+c.width+10+"px";g.style.width=c.width+"px"}return a._lightbox}var l=f+"_here_iframe_";a.config.buttons_left=[];a.config.buttons_right=
[];a._getLightbox=a.getLightbox;a.config.lightbox.sections=[{type:"frame",name:"box"}];a._cust_string_to_date=function(b){return a.templates.xml_date(b)};a._cust_date_to_str=function(b){return a.templates.xml_format(b)};a._deep_copy=function(b){if(typeof b=="object"){var a=Object.prototype.toString.call(b)=="[object Date]"?new Date(b):Object.prototype.toString.call(b)=="[object Array]"?[]:{},c;for(c in b)a[c]=j._deep_copy(b[c])}else a=b;return a};c.type=="external"?(a.attachEvent("onBeforeLightbox",
function(){a._custom_box_stage=0;return!0}),a.getLightbox=k,a._setLightboxValues=function(b,g){b=document.getElementById(l);try{switch(a._custom_box_stage){case 0:if(!a.dataProcessor){var d=a.dataProcessor=new DataProcessor;d.init(a)}var d=a.dataProcessor||d,e=d._getRowData(g),m=(c.view||"").indexOf("?")===-1?"?":"&",h="<form action='/"+c.view+m+"id="+encodeURIComponent(g)+"' method='POST'>",f;for(f in e)h+="<input type='hidden' name='"+f+"'/>";h+="</form>";var i=b.Document?b.Document.body:b.contentDocument.body;
i.innerHTML=h;var j=0;for(f in e)i.firstChild.childNodes[j++].value=e[f];i.firstChild.submit();break;case 1:if(!b.contentWindow.lightbox){var k=b.contentWindow;b.contentWindow.lightbox={close:function(){a._remove_customBox()}}}a.callEvent("onLightbox",[g]);break;case 2:if(!b)return;i=b.Document?b.Document.body:b.contentDocument.body;a._doLAction(i.textContent||i.innerText);a._remove_customBox()}}catch(n){a._remove_customBox()}a._custom_box_stage++},a._remove_customBox=function(){a._lightbox?a.endLightbox(!1,
a._lightbox):a.endLightbox(!1);a.callEvent("onAfterLightbox",[])},a._doLAction=function(b){try{var c=eval("("+b+")");if(c){var d=c.data;if(d.start_date&&d.end_date)d.start_date=a._cust_string_to_date(c.data.start_date),d.end_date=a._cust_string_to_date(c.data.end_date);var e=c.action;switch(c.action){case "insert":a._loading=!0;a.addEvent(d);a._loading=!1;e="inserted";break;case "update":var f=a.getEvent(c.sid),h;for(h in d)f[h]=d[h];a.event_updated(f);a.updateEvent(c.sid);e="updated";break;case "delete":a.deleteEvent(c.sid,
!0),e="deleted"}a.dataProcessor.callEvent("onAfterUpdate",[c.sid,e,c.id,c])}}catch(j){}},a.form_blocks.frame={render:function(){return"<div style='display:inline-block; height:"+c.height+"px'></div>"},set_value:function(b,g,d){a._last_id=d.id;var e='<iframe id="'+l+"\" frameborder='0' onload='"+f+"._setLightboxValues(this, "+f+"._last_id)' src=''";if(c.width||c.height)e+=" style='";if(c.width)e+="width:"+c.width+"px;",b.style.width=c.width+"px";if(c.height)e+="height:"+c.height+"px;",b.style.height=
c.height+"px";if(c.width||c.height)e+=" '";e+="><html></html></iframe>";b.innerHTML=e;if(c.classname)b.className=c.classname;return!0},get_value:function(){return!0},focus:function(){return!0}},a._addEventFromFrame=function(){var a={}}):(a.form_blocks.frame={render:function(){var a='<iframe  id="'+f+"_here_iframe_\" onload='"+f+"._addLightboxInterface(this)' frameborder='0' src='"+c.view+"'";if(c.width||c.height)a+=" style='";c.width&&(a+="width:"+c.width+"px;");c.height&&(a+="height:"+c.height+"px;");
if(c.width||c.height)a+=" '";a+=" ></iframe>";return a},set_value:function(a,c,d){if(a.contentWindow&&a.contentWindow.setValues){if(a.contentWindow.document.getElementsByTagName("form").length==1)a.contentWindow.document.getElementsByTagName("form")[0].reset();else{var d=a.contentWindow.getValues(),e;for(e in d)d[e]="";a.contentWindow.setValues(d)}a.contentWindow.setValues(d)}},get_value:function(b){return a._deep_copy(b.contentWindow.getValues())},focus:function(){return!0}},a.getLightbox=k,a._addLightboxInterface=
function(b){if(!b.contentWindow.lightbox)b.contentWindow.lightbox={};b.contentWindow.lightbox.save=function(){var c=a.getEvent(a.getState().lightbox_id),d=b.contentWindow.getValues(),f;for(f in d)c[f]=d[f];a.endLightbox(!0,a._lightbox)};b.contentWindow.lightbox.close=function(){a.endLightbox(!1,a._lightbox)};b.contentWindow.lightbox.remove=function(){var b=a.locale.labels.confirm_deleting;if(!b||confirm(b))a.deleteEvent(a._lightbox_id),a._new_event=null;a.endLightbox(!0,a._lightbox)};if(b.contentWindow.document.getElementsByTagName("form").length==
1)b.contentWindow.document.getElementsByTagName("form")[0].reset();else if(b.contentWindow.getValues&&b.contentWindow.setValues){var c=b.contentWindow.getValues(),d;for(d in c)c[d]="";b.contentWindow.setValues(c)}b.contentWindow.setValues&&b.contentWindow.setValues(a.getEvent(a._lightbox_id));a.callEvent("onLightbox",[a._lightbox_id])})}});
